export type {
  Broadcast,
  BroadcastAnalytics,
  BroadcastExclusionReason,
  BroadcastExclusionSummary,
  BroadcastPreview,
  BroadcastRecipient,
  BroadcastRecipientStatus,
  BroadcastStatus,
  CreateBroadcastOptions,
  DuplicateBroadcastOptions,
  ListBroadcastRecipientsOptions,
  ListBroadcastsOptions,
  PreviewBroadcastOptions,
  SendBroadcastOptions,
  UpdateBroadcastOptions,
} from "./broadcasts/types.js";
export type {
  Campaign,
  CampaignAnalytics,
  CampaignCostEstimate,
  CampaignExclusionReason,
  CampaignExclusionSummary,
  CampaignPreview,
  CampaignRecipient,
  CampaignRecipientStatus,
  CampaignSmsEncoding,
  CampaignStatus,
  CreateCampaignOptions,
  DuplicateCampaignOptions,
  ListCampaignRecipientsOptions,
  ListCampaignsOptions,
  SendCampaignOptions,
  UpdateCampaignOptions,
} from "./campaigns/types.js";
export type { DugbleOptions } from "./client.js";
export { Dugble } from "./client.js";
export type {
  ContactProperty,
  ContactPropertyDeleteResponse,
  ContactPropertyFallback,
  ContactPropertyList,
  ContactPropertyMutationResponse,
  ContactPropertyType,
  CreateContactPropertyOptions,
  ListContactPropertiesOptions,
  UpdateContactPropertyOptions,
} from "./contact-properties/types.js";
export type {
  Contact,
  ContactSegmentMembership,
  ContactTopic,
  ContactTopicList,
  ContactTopicSubscription,
  CreateContactOptions,
  ListContactsOptions,
  ListContactTopicsOptions,
  SmsConsentSource,
  SmsConsentStatus,
  UpdateContactOptions,
  UpdateContactTopic,
  UpdateContactTopicsResponse,
} from "./contacts/types.js";
export type {
  CreateDomainOptions,
  CreateDomainResponse,
  Domain,
  DomainCapabilities,
  DomainHealthStatus,
  DomainProvisioningResponse,
  DomainRecordStatus,
  DomainStatus,
  DomainTlsMode,
  DomainVerificationRecord,
} from "./domains/types.js";
export type {
  Email,
  EmailAddress,
  EmailAttachment,
  EmailEvent,
  EmailEventList,
  EmailSummary,
  EmailTag,
  ListEmailEventsOptions,
  ListEmailsOptions,
  MutationResponse,
  SendEmailOptions,
  SendEmailResponse,
  UpdateEmailOptions,
} from "./emails/types.js";
export type {
  DugbleErrorResponse,
  DugbleResponse,
  IdempotentRequestOptions,
  RequestOptions,
} from "./interfaces.js";
export type {
  CreateSegmentOptions,
  ListSegmentContactsOptions,
  ListSegmentsOptions,
  Segment,
  SegmentContact,
} from "./segments/types.js";
export type {
  CreateSenderIdOptions,
  SenderId,
  SenderIdStatus,
} from "./sender-ids/types.js";
export type {
  ListSmsEventsOptions,
  ListSmsOptions,
  SendSmsOptions,
  SendSmsResponse,
  SmsDestination,
  SmsEvent,
  SmsEventList,
  SmsFailure,
  SmsMessage,
  UpdateSmsOptions,
} from "./sms/types.js";
export type {
  BatchAddSuppressionsOptions,
  BatchAddSuppressionsResponse,
  BatchRemoveSuppressionsOptions,
  BatchRemoveSuppressionsResponse,
  CreateSuppressionOptions,
  ListSuppressionsOptions,
  Suppression,
  SuppressionDeleteResponse,
  SuppressionList,
  SuppressionMutationResponse,
  SuppressionOrigin,
} from "./suppressions/types.js";
export type {
  CreateTemplateOptions,
  ListTemplatesOptions,
  ListTemplateVersionsOptions,
  PreviewTemplateOptions,
  Template,
  TemplateDeleteResponse,
  TemplateList,
  TemplateListItem,
  TemplateMutationResponse,
  TemplatePreview,
  TemplateRevertResponse,
  TemplateStatus,
  TemplateTestSendResponse,
  TemplateVariable,
  TemplateVariableFallback,
  TemplateVariableOptions,
  TemplateVariableType,
  TemplateVersion,
  TemplateVersionVariable,
  TestSendTemplateOptions,
  UpdateTemplateOptions,
} from "./templates/types.js";
export type {
  CreateTopicOptions,
  ListTopicsOptions,
  Topic,
  TopicDeleteResponse,
  TopicList,
  TopicMutationResponse,
  TopicSubscription,
  TopicVisibility,
  UpdateTopicOptions,
} from "./topics/types.js";
